language: node_js
node_js:
  - "stable"
env:
  - NEO4J_VERSION="3.5.14"
dist: xenial
snaps:
  - docker
services:
  - neo4j
jobs:
  include:
    - stage: "Backend"
      install:
        - cd ./ToDoApp/Backend
        - npm install
      before_install:
      - docker-compose up
      - wait-on http://localhost:7474
      script:
        - npm test
    - stage: "Frontend"
      install:
        - cd ./ToDoApp/Frontend
        - npm install
      script:
        - npm test
        - npm run lint


before_script:
- docker-compose up
- wait-on http://localhost:7474

script:
- echo "Run your tests here"