language: node_js
node_js:
  - "stable"
jobs:
  include:
    - stage: "Backend"
      install:
        - cd ./ToDoApp/Backend
        - npm install
      script:
        - npm test
    - stage: "Frontend"
      install:
        - cd ./ToDoApp/Frontend
        - npm install
      script:
        - npm test
        - npm run lint
