language: node_js
node_js:
  - "stable"
services:
- docker
before_install:
- docker run --name todo_neo4j -p7474:7474 -p7687:7687 -d --env NEO4J_AUTH=neo4j/password neo4j:latest
jobs:
  include:
    - stage: "Backend"
      install:
        - cd ./ToDoApp/Backend
        - npm install
      script:
        - npm test --detectOpenHandles
    - stage: "Frontend"
      install:
        - cd ./ToDoApp/Frontend
        - npm install
      script:
        - npm test
        - npm run lint

