language: node_js
node_js:
  - "stable"
jobs:
  include:
    - stage: "Backend"
      env:
      - NEO4J_VERSION="3.5.14"
      before_install:
      - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
      - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
      - neo4j-community-$NEO4J_VERSION/bin/neo4j-admin set-initial-password password
      - neo4j-community-$NEO4J_VERSION/bin/neo4j start
      install:
        - cd ./ToDoApp/Backend
        - npm install
      script:
        - npm test
    - stage: "Frontend"
      install:
        - cd ./ToDoApp/Frontend
        - npm install

      before_script:
      - npm run ./ToDoApp/Backend:seed
      - wait-on http://localhost:7474
      script:
        - npm test
        - npm run lint
